import typing as t

import pydantic as pdt
from aiida.plugins import WorkflowFactory

from common_workflow_schemas.common.context import BASE_PREFIX
from common_workflow_schemas.common.field import MetadataField
from common_workflow_schemas.common.mixins import SemanticModel
from common_workflow_schemas.schemas.relax import TotalEnergy, TotalMagnetization

SM = t.TypeVar("SM", bound=SemanticModel)


class CompositeInputs(t.Generic[SM]):
    sub_process_class: t.Annotated[
        str,
        MetadataField(
            description=(
                "The quantum engine that will be used for the relaxation given as a "
                "valid workflow entry point for a common relax implementation. To see "
                "a list of all available entry points, use `verdi plugin list "
                "aiida.workflows`. Any entry point that starts with "
                "`common_workflows.relax.` can be used."
            ),
            iri=f"{BASE_PREFIX}/composite/SubProcessClass",
        ),
    ]
    generator_inputs: t.Annotated[
        SM,
        MetadataField(
            description=(
                "The inputs to pass to the generator process. If not specified, the "
                "default inputs will be used."
            ),
            iri=f"{BASE_PREFIX}/composite/GeneratorInputs",
        ),
    ]
    sub_process: t.Annotated[
        dict[str, t.Any],
        MetadataField(
            description=(
                "Code-dependent inputs overridding those generated by "
                "`generator_inputs`. The inputs must be valid ports of the "
                "`sub_process_class`."
            ),
            iri=f"{BASE_PREFIX}/composite/SubProcess",
        ),
    ]

    @pdt.field_validator("sub_process_class")
    def _validate_sub_process_class(self, sub_process_entry_point: str):
        if not sub_process_entry_point.startswith("common_workflows.relax."):
            raise ValueError(
                f"`sub_process_class` should start with 'common_workflows.relax.', got "
                f"'{sub_process_entry_point}'"
            )
        return sub_process_entry_point

    @pdt.field_validator("sub_process")
    def _validate_sub_process(self, sub_process_dict: dict[str, t.Any]):
        workchain = WorkflowFactory(self.sub_process_class)
        for key in sub_process_dict:
            if not hasattr(workchain, key):
                raise ValueError(
                    f"Invalid input key '{key}' for sub-process class"
                    f"'{self.sub_process_class}'"
                )


class CompositeOutputs(SemanticModel):
    total_energies: t.Annotated[
        list[TotalEnergy],
        MetadataField(
            description="The computed total energy for each sub-process.",
            container=list,
        ),
    ]
    total_magnetizations: t.Annotated[
        t.Optional[list[TotalMagnetization]],
        MetadataField(
            description=(
                "The total magnetization of the final structure of each sub process, "
                "if returned by the underlying common relax workflow."
            ),
            container=list,
        ),
    ]
